apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    - cron: 51 10 * * *
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          if [ '${{ cloudbees.event_name}}' = schedule  ]; then
            echo "hello cron"
          else
            echo "hello world"
          fi  
